import { type Metadata } from "next";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { Lexend_Mega, Lexend } from "next/font/google";
import "./globals.css";

import Header from "./_components/Header";
import { Loader } from "lucide-react";
import { Toaster } from "sonner";

const lexendSans = Lexend({
  variable: "--font-lexend-sans",
  subsets: ["latin"],
});

const lexendMega = Lexend_Mega({
  variable: "--font-lexend-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${lexendSans.variable} ${lexendMega.variable} antialiased`}
        >
          <ClerkLoading>
            <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-white bg-opacity-90 z-50">
              <Loader className="w-10 h-10 animate-spin" />
            </div>
          </ClerkLoading>

          <ClerkLoaded>
            <Header />

            {children}
          </ClerkLoaded>

          <Toaster position="top-center" />
        </body>
      </html>
    </ClerkProvider>
  );
}
